const express = require('express')
// const sql = require('mssql')
// const conn = require('./conn')
const sinhVienRouter = require('./routes/sinhvien.route')
const lopRouter = require('./routes/lop.route')
const monhocRouter = require('./routes/monhoc.route')
const diemRouter = require('./routes/diem.route')
const authRoute = require('./routes/auth.route')
const cookieController = require('./controllers/getCookies.controller')
const requireLogin = require('./validation/validate.requireLogin')
const logoutController = require('./controllers/logout.controller')
const createUserRoute = require('./routes/createUser.route')
const cookieParser = require('cookie-parser')
 
const app = express()
const port = 3001
app.set('view engine','pug')
app.set('views','./views')
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cookieParser())
app.use(express.static('public'))


// app.use(requireLogin.requireLogin)
app.use(cookieController.getCookies)            
app.use('/login',authRoute)
app.use('/',requireLogin.requireLogin,sinhVienRouter)
app.use('/lop',requireLogin.requireLogin,lopRouter)
app.use('/monhoc',requireLogin.requireLogin,monhocRouter)
app.use('/diem',requireLogin.requireLogin,diemRouter)
app.get('/logout',logoutController.logout)
app.use('/create',requireLogin.requireLogin,createUserRoute)
app.listen(port,() => console.log(`Example app listening at http://localhost:${port}`))
